config/routes.rb
Rails.application.routes.draw do
  # get 'requests/index'
  # get 'requests/create'
  devise_for :users
  root to: 'custodies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :messages, only: [:index, :create]

  root to: 'custodies#index'


  resources :custodies, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      patch 'switch'
    end
  end
  resources :messages
  resources :media, only: [:index, :show, :new, :create, :destroy]
  resources :users, except: [:index, :new, :create, :show, :edit]

  get :profile, to: 'users#profile'
  get :edit_profile, to: 'users#edit_profile'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
  has_many :parents, class_name: 'User'
end

app/models/custody.rb
class Custody < ApplicationRecord
  belongs_to :user

  has_many :media, dependent: :destroy

  validates :day_on, presence: true

  def future?
    day_on > Date.today
  end

  def poor?
    media.blank? && title.blank? && text.blank?
  end

  def switch
    self.user = user.child.parents.where.not(id: user.id).first
    self.change_at = Time.now
    save
  end
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :custody
  mount_uploader :photo, PhotoUploader
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'

  before_validation :set_current_time

  validates :body, presence: true
  validates :send_at, presence: true

  scope :between, lambda { |sender, receiver|
    where("(sender_id = ? AND receiver_id = ?
          OR (receiver_id = ? AND sender_id = ?)",
          sender.id, receiver.id, sender.id, receiver.id)
  }

  private

  def set_current_time
    self.send_at = Time.now
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :child, optional: true

  has_many :custodies
  # has_many :unread_messages, -> { where(read: false) },
  #          class_name: 'Message',
  #          foreign_key: :receiver_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def ex_partner
    User.where(child_id: child_id).where.not(id: id).first
  end

  def class_css
    if first_partner?
      'bg-user-1'
    else
      'bg-user-2'
    end
  end

  def first_partner?
    return true unless ex_partner

    self.created_at < ex_partner.created_at
  end

  def fixed_ex_partner
    child.parents.where.not(id: id).last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # app/controllers/application_controller.rb

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end
end

app/controllers/custodies_controller.rb
class CustodiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_custodies, only: %i[show edit update switch]

  def index
    params[:number] ||= 0

    @custodies = Custody.where(day_on: start_date..end_date).sort
    @custody_today = Custody.where(day_on: Date.today)[0]

    render :months if params[:range] == 'month'

    @sender   = current_user
    @receiver = User.where(child_id: current_user.child_id).where.not(id: current_user.id).first
    p "rediriger vers 'inviter l'autre parent" if @receiver.nil?
    @message  = Message.new
    @messages = Message.all
  end

  def show
    @custody = Custody.find(params[:id])
    @media   = @custody.media
  end

  def new
    @custody = Custody.new
  end

  def create
    @custody = Custody.new(custodies_params)
    if @custody.save!
      redirect_to custody_path(@custody.day_on.day)
    else
      render :new
    end
  end

  def edit
    @image = @custody.media.build
    @number = params[:number]
  end

  def update
    if @custody.update(custodies_params)
      if params[:custody][:media].present?
        params[:custody][:media].each do |image|
          @image = @custody.media.create!(photo: image)
        end
      end
      redirect_to custodies_path(number: params[:custody][:number], anchor: "custody#{@custody.id}")
    else
      render :edit
    end
  end

  # PATCH /custodies/:id/switch
  def switch
    @custody.switch
    redirect_back(fallback_location: custodies_path)
  end

  private

  def set_custodies
    @custody = Custody.find(params[:id])
  end

  def custodies_params
    params.require(:custody)
          .permit(:title,
                  :text,
                  :day_on,
                  :user_id,
                  media_attributes: [:photo])
  end

  def start_date
    if params[:range] == 'month'
      current_monday
    else
      current_monday + (7 * params[:number].to_i).day
    end
  end

  def end_date
    if params[:range] == 'month'
      current_monday + 27.day
    else
      start_date + 6.day
    end
  end

  def current_monday
    Date.parse("Monday").to_time
  end

  # def number_for_custody
  #   ((@custody.day_on - Date.parse("sunday")) / 7).to_i - 1
  # end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_media, only: %i[show]

  def index
    @media = Medium.all
  end

  def show
  end

  def new
    @medium = Medium.new
  end

  def create
    @medium = Medium.new(media_params)
    if @medium.save!
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def set_media
    @medium = Medium.find(params[:id])
  end

  def media_params
    params.require(:medium)
          .permit(:photo,
                  :custody_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message  = Message.new(message_params)
    @user     = User.find(params[:message][:receiver_id])
    @message.save!
    broadcast_message
  end

  private

  def message_params
    params.require(:message).permit(:body, :sender_id, :receiver_id)
  end

  def broadcast_message
    ActionCable.server.broadcast(
      "child_id_#{@user.child.id}",
      message_partial: ApplicationController.renderer.render(
        partial: "shared/message",
        locals: { message: @message, user: current_user }
      ),
      current_user_id: current_user.id
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :update]

  def profile
    @parent1 = current_user
    @parent2 = current_user.fixed_ex_partner
  end

  def edit_profile
    @parent1 = current_user
  end

  def update
    @parent1 = current_user.update(users_params)
    redirect_to profile_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:email, :first_name, :last_name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def opposite_parent_for(custody, user)
    user.child.parents.where.not(id: custody.user.id).first
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/custodies/edit.html.erb
<div class="header">
    <h1> <%= link_to "Simya", custodies_path %> </h1>
    <h2>Facilitez-vous la garde alternée</h2>
  </div>
<!-- Métadonnées -->
<%= content_for(:meta_title) do  %>
  Créer un souvenir
<% end %>

<div class="wrapper">


<div class="main-container">

  <!-- Bouton fermeture du formulaire -->
  <%= link_to custodies_path do  %>
    <button type="button" id="button-close-month" class="button-circle" data-toggle="tooltip" data-placement="bottom" title="Fermer" >
      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
    </button>
  <% end %>

  <% if @custody.day_on > Date.today %>

    <div class="form-container">
      <%= simple_form_for @custody do |f| %>
        <%= f.input  :day_on %>
        <%= f.association :user, label_method: :first_name, input_html: { value:  opposite_parent_for(@custody, current_user).id }, as: :hidden %>
        <%= f.button :submit, label= "Modifier le planning", class: 'button' %>
      <% end %>
    </div>
  <% else %>

    <div class="form-container ">
      <div class="justify-center">
        <span class="day "><%= l(@custody.day_on, format: "%A")%></span>
        <span class="date"><%= @custody.day_on.day %></span>
        <span class="month"><%= l(@custody.day_on, format: "%B")%></span>
      </div>

      <%= simple_form_for (@custody) do |f| %>
        <%= f.input :title %>
        <%= f.input :text %>
        <%= f.file_field :media, multiple: true  %>
        <%= f.input :number, :as => :hidden, :input_html => { :value => @number } %>
        <%= f.button :submit, label= "Créer un souvenir", class: 'button btn-edit' %>
      <% end %>
    </div>
  <% end %>
</div> <!-- end container -->

</div>

app/views/custodies/index.html.erb
<div class="header-fix">

  <div class="header">
    <h1> <%= link_to "Simya", custodies_path %> </h1>
    <h2>Facilitez-vous la garde alternée</h2>
  </div>
  <!-- Bouton affichage mensuel -->
  <div class="month-container">
    <!-- btn mois + icon calendar -->
    <%= link_to custodies_path(range: "month") do %>
      <p class="display-month " data-toggle="tooltip" data-placement="bottom" title="Voir le mois">
        <span class="glyphicon glyphicon-calendar padding" aria-hidden="true"></span>
          <%= l(@custodies.first.day_on, format: "%B %Y") %>
      </p>
    <% end %>

    <div class="header-right">
    <!-- Bouton retour Aujourd'hui -->
    <%= link_to custodies_path(number: (0)) do %>
      <span class="button-today" data-toggle="tooltip" data-placement="bottom" title="Revenir à la semaine en cours">Aujourd'hui</span>
    <% end %>

    <!-- bouton deconnecter -->
    <%= link_to destroy_user_session_path,method: :delete do  %>
      <button type="button" class="log-out" data-toggle="tooltip" data-placement="bottom" title  ="Se déconnecter" >
        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
      </button>
    <% end %>
    <!-- fin btn -->
    </div>


  </div>
</div>
<!-- début itération des cards -->
<div class="custodies-container">

  <% @custodies.each do |custody| %>

    <% if custody.day_on == Date.today %>

      <div class="custody today <%=  custody.user.first_partner? ? 'bg-user-1' : "bg-user-2" %>">

        <div class="container-tag">
          <span class="day font-size"><%= l(custody.day_on, format: "%A")%></span>
          <span class="date font-size"><%= custody.day_on.day %></span>
          <span class="tag"> Aujourd'hui</span>
        </div>
    <% else %>

      <div id="custody<%=custody.id%>" class="custody  <%= custody.user.first_partner? ? 'bg-user-1' : "bg-user-2" %>">
        <span class="day "><%= l(custody.day_on, format: "%A")%></span>
        <span class="date"><%= custody.day_on.day %></span>
        <span id="user-custody"><%= custody.user.first_name %></span>
    <% end %>

    <ul class="list-inline button-container">

      <% if custody.future? %>
        <!-- bouton de modification de planning -->
        <li>
          <%= link_to switch_custody_path(custody), method: :patch do  %>
            <button type="button" class="button-circle align-right <% if custody.change_at  %> notification <% end %>"  data-toggle="tooltip" data-placement="bottom" title="Changer le planning">
              <span class="glyphicon glyphicon-transfer" aria-hidden="true"></span>
            </button>
          <% end %>
        </li>

      <% else %>


          <!-- button edit sur la card a tout moment-->
          <li>
            <%= link_to edit_custody_path(custody, number: params[:number]) do  %>
              <button type="button" class="button-circle" data-toggle="tooltip" data-placement="bottom" title="Créer un souvenir pour cette journée" >
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
              </button>
            <% end %>
          </li>

      <% end %>

      <li>
        <!-- Avatar -->
        <%= link_to profile_path  do  %>
          <div class="avatar" data-toggle="tooltip" data-placement="bottom" title="Voir mon profil"
        style="background-image: url('<%= cl_image_path custody.user.avatar, height: 300, width: 400, crop: :fill %>')">
          </div>
        <% end %>
      </li>
    </ul>

    <div class="img-txt-container">
      <div class="text-container">
        <h4><%= custody.title %></h4>
        <p id="text-custody"><%= custody.text %></p>
      </div>

      <div class="img-container">
        <% unless custody.media[0].nil? %>
          <p class="img-custody" style="background-image:
          url('<%= cl_image_path custody.media[0].photo.url, height: 300, width: 400, crop: :fill %>')">
          </p>
        <% end %>
      </div>
    </div>
        <!-- photoswipe -->
        <div class="thumbail-container">
          <div class="my-gallery " itemscope itemtype="http://schema.org/ImageGallery">
            <% custody.media.each do |photo|  %>
              <figure class="inline" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
                <a href="<%= "#{photo.photo}" %>" itemprop="contentUrl" data-size="500x600">
                  <span class="thumbails" temprop="thumbnail" alt="Image description">
                  <%= cl_image_tag("#{photo.photo}", width: 30, height: 30, crop: :fill) %>
                  </span>
                </a>
              </figure>
            <% end %>
          </div>
        </div>
        <!-- photoswipe -->
      </div>
  <% end %>
</div>


<!-- Bouton semaine précèdente -->
  <div class="btn-previous">
    <%= link_to custodies_path(number: (params[:number].to_i - 1)) do %>
      <button type="button" class="button-circle fixed left"  data-toggle="tooltip" data-placement="bottom" title="Voir semaine précédente">
        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
      </button>
    <% end %>
  </div>


<!-- Bouton semaine suivante -->
<div class="btn-next">
  <%= link_to custodies_path(number: (params[:number].to_i + 1)) do %>
    <button type="button" class="button-circle fixed right"  data-toggle="tooltip" data-placement="bottom" title="Voir semaine suivante">
      <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
    </button>
  <% end %>
</div>

<%= render 'shared/messages', receiver: @receiver, sender: @sender,  message: @message, messages: @messages %>

<button type="button" class="button-open-chat" data-toggle="tooltip" data-placement="top" title="Ouvrir le chat" >
  <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
</button>


<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
  <!-- Background of PhotoSwipe.
       It's a separate element, as animating opacity is faster than rgba(). -->
  <div class="pswp__bg"></div>
    <!-- Slides wrapper with overflow:hidden. -->
  <div class="pswp__scroll-wrap">
    <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
    <!-- don't modify these 3 pswp__item elements, data is added later on. -->
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>
    <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
    <div class="pswp__ui pswp__ui--hidden">
      <div class="pswp__top-bar">
        <!--  Controls are self-explanatory. Order can be changed. -->
        <div class="pswp__counter"></div>
        <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
        <!-- <button class="pswp__button pswp__button--share" title="Share"></button> -->
        <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
        <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
        <!-- Preloader demo https://codepen.io/dimsemenov/pen/yyBWoR -->
        <!-- element will get class pswp__preloader--active when preloader is running -->
        <div class="pswp__preloader">
          <div class="pswp__preloader__icn">
            <div class="pswp__preloader__cut">
              <div class="pswp__preloader__donut"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
        <div class="pswp__share-tooltip"></div>
      </div>
      <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
      <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
      <div class="pswp__caption">
        <div class="pswp__caption__center"></div>
      </div>
    </div>
  </div>
</div>

app/views/custodies/months.html.erb
<h1 class="month-month">
  <%= l(@custodies.first.day_on, format: "%B").capitalize%>
  <% if l(@custodies.first.day_on, format: "%B") != l(@custodies.last.day_on, format: "%B") %>
    ~ <%= l(@custodies.last.day_on, format: "%B").capitalize%>
  <% end %>
</h1>

<%= link_to custodies_path do  %>
  <button type="button" id="button-close-month" class="button-circle" data-toggle="tooltip" data-placement="bottom" title="Fermer" >
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
  </button>
<% end %>

<div class="calendrier">

  <% @custodies.each do |custody| %>

    <div class="custodies-months <%= custody.user.first_partner? ? 'bg-user-1' : "bg-user-2" %>">
      <span class="date-day"><%= l(custody.day_on, format: "%a")%></span>
      <span class="date-month"><%= l(custody.day_on, format: "%d")%></span>
      <div class="avatar" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.0)), url('<%= cl_image_path custody.user.avatar, height: 300, width: 400, crop: :fill %>')">
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

      <title><%= meta_title %></title>
        <meta name="description" content="<%= meta_description %>">

        <!-- Facebook Open Graph data -->
        <meta property="og:title" content="<%= meta_title %>" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="<%= request.original_url %>" />
        <meta property="og:image" content="<%= meta_image %>" />
        <meta property="og:description" content="<%= meta_description %>" />
        <meta property="og:site_name" content="<%= meta_title %>" />

        <!-- Twitter Card data -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
        <meta name="twitter:title" content="<%= meta_title %>">
        <meta name="twitter:description" content="<%= meta_description %>">
        <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
        <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stylesheet_pack_tag 'application', media: 'all' %> <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <%= favicon_link_tag asset_path('favicon.png') %>


  </head>
  <body>
    <%= render 'shared/flashes' %>
    <% unless params[:range] == 'month' %>

    <% end %>


    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <%= yield(:after_js) %>
   <%= render 'shared/footer' %>
  </body>
</html>

app/views/messages/create.js.erb
document.querySelector("#t-message").value = "";

app/views/offers/show.html.erb
<% content_for :meta_title, "#{@offer.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @offer.description %>
<% content_for :meta_image, cl_image_path(@offer.photo.path) %>

app/views/shared/_boutton_chat.html.erb
<button type="button" class="button-open-chat" data-toggle="tooltip" data-placement="top" title="Ouvrir le chat" >
  <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
</button>

<button type="button" class="button-circle btn-close-chat" data-toggle="tooltip" data-placement="top" title="Fermer le chat" >
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
</button>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="flashes">
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
</div>
<% end %>
<% if alert %>
<div class="flashes">
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <p>&copy 2019 - Simya</p>
</footer>

app/views/shared/_header.html.erb
<div class="header">
<h1> <%= link_to "Simya", custodies_path %> </h1>
<h2>Facilitez-vous la garde alternée</h2>
</div>

app/views/shared/_message.html.erb
<% if user == message.sender  %>
  <div class="message-wrapper sender">
    <div class="message-container">
      <div class="message-time" id="time-right">
        <span><%=time_ago_in_words(message.send_at) %></span>
      </div>
      <div class="message-content">
        <p ><%= message.body %></p>
      </div>
    </div>
  </div>
<% else %>
  <div class="message-wrapper receiver">
    <div class="message-container">
      <div class="message-time" id="time-left">
        <span><%=time_ago_in_words(message.send_at) %></span>
      </div>
      <div class="message-content">
        <p><%= message.body %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="message">

<div class="column">
  <div  class="avatar margin"
        style="background-image: url('<%= cl_image_path receiver.avatar, height: 300, width: 400, crop: :fill %>')">
  </div>

  <h4 class="title-chat">
    Envoyer un message à <%= receiver.first_name %>
  </h4>

  <button type="button"
          class="button-close-chat btn-close-chat"
          data-toggle="tooltip"
          data-placement="top"
          title="Fermer le chat" >
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
  </button>
</div>
  <div class="message-user">
      <% messages.each do |message| %>
        <% if message.body %>
          <%= render "shared/message", message: message, user: current_user %>
        <% end %>

      <% end %>

  </div>

  <div>
    <%= form_for message, remote: true do |f| %>
      <div>
        <%= f.text_area :body,
                        placeholder: "Tapez votre message ici.",
                        id: "t-message",
                        class: "form-control" %>
      </div>
      <div>
        <%= f.text_field :sender_id, value: current_user.id,
                         type: "hidden"  %>
        <%= f.text_field :receiver_id, value: receiver.id,
                         type: "hidden" %>
        <%= f.submit "Envoyer", class: "chat" %>
      </div>
    <% end %>
  </div>
</div>



<% content_for :after_js do %>
  <script>

    function scrollToBottom() {
      const objDiv = document.querySelector(".message-user");
      objDiv.scrollTop = objDiv.scrollHeight;
    }

    function updateLastMessageClass(message_sender_id) {
      const lastMessage = document.querySelector(".message-wrapper:last-child");
      lastMessage.classList.remove("sender");

      if (message_sender_id == <%= current_user.id %>) {
        console.log("sender")
        lastMessage.classList.add("sender");
      } else {
        console.log("receiver");
        lastMessage.classList.add("receiver");
      }
    }
    scrollToBottom();

    App['child_id_<%= current_user.child.id %>'] = App.cable.subscriptions.create(
        { channel: 'ChatRoomsChannel', child_id: <%= current_user.child.id %> },
        { received: (data) => {
          document.querySelector(".message-user").insertAdjacentHTML('beforeend', data.message_partial);

          updateLastMessageClass(data.current_user_id);

          const btn = document.querySelector(".button-open-chat");
          const chat = document.querySelector(".message");
          chat.classList.add("display");
          btn.style.display = "none";

          scrollToBottom();
        }

      })
  </script>
<% end %>

app/views/shared/_user_profile.html.erb
 <div id="user-show"class="user <%= background_class %>">

  <div>
    <%=cl_image_tag "#{user.avatar}", class: "user-avatar"%>
  </div>

  <div class="user-information">
      <div class="user-fullname">
        <p><strong><%= user.last_name %>     <%= user.first_name %></strong></p>
      </div>
      <div class="user-email">
        <p><strong><%= user.email %></strong></p>
      </div>
      <div class="user-phone">
        <p><strong><%= user.phone %></strong></p>
      </div>
  </div>
</div>

app/views/users/edit_profile.html.erb
<%= content_for(:meta_title) do  %>
  Modifier mon profil
<% end %>

<div class="main-container">
  <div class="form-container">
    <%= simple_form_for @parent1 do |f| %>
            <%= f.input :email %>
            <%= f.input :phone %>
            <label class="label-avatar" for="label-avatar">Télécharger une photo</label>
            <%= f.file_field :avatar %>
            <%= f.button :submit, label= "Modifier mon profil", class: 'button btn-edit' %>
    <% end %>
  </div> <!-- end form container -->
</div> <!-- end container -->

app/views/users/profile.html.erb
<%= content_for(:meta_title) do  %>
  Profil
<% end %>

<div class="user-container">
  <%= render 'shared/user_profile', user: @parent1, background_class: @parent1.class_css %>
    <div class="child-container">
      <div class="child">
        <div class="child-info">
          <p><strong> <%= @parent1.child.first_name %>  <%= @parent1.child.last_name %></strong></p>
          <p><strong><%= @parent1.child.birthday %></strong></p>
        </div>
      </div>

        <ul class="list-inline position">
            <li><%= link_to custodies_path do  %>
              <button type="button" class="button-circle" data-toggle="tooltip" data-placement="bottom" title  ="Voir le planning" >
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
              </button>
              <% end %></li>

            <li> <%= link_to edit_profile_path do  %>
                <button type="button" class="button-circle" data-toggle="tooltip" data-placement="bottom" title  ="Modifier mon profil" >
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </button>
                <% end %></li>

            <li> <%= link_to destroy_user_session_path,method: :delete do  %>
              <button type="button" class="button-circle" data-toggle="tooltip" data-placement="bottom" title  ="Se déconnecter" >
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
              </button>
              <% end %></li>
        </ul>
    </div>

      <%= render 'shared/user_profile', user: @parent2, background_class: @parent2.class_css %>

</div>